---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fastapi
  namespace: dev-ns
spec:
  serviceName: fast-service
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fnej/fastapi-backend:v0.0.6
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /app/saved_files
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: gp2
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 5Gi
