---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-claim
  namespace: dev-ns
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  resources:
    requests:
      storage: 5Gi # ignored, required
  volumeName: s3-pv
