apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: fnej/fastapi-backend:v0.0.6
        ports:
          - name: http
            containerPort: 8000
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 100m
        volumeMounts:
        - mountPath: "/app/saved_files"
          name: s3-storage
      volumes:
      - name: s3-storage
        persistentVolumeClaim:
          claimName: s3-claim