---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastapi-pvc
  namespace: dev-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi # Don't matter, it's elastic
