---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-aws-secrets
  namespace: dev-ns
spec:
  provider: aws
  parameters:
    region: ca-central-1
    objects: |
      - objectName: staging/myapp-secret-v4
        objectType: secretsmanager
        jmesPath:
            - path: username
              objectAlias: myusername
            - path: password
              objectAlias: mypassword
            - path: airflow
              objectAlias: myairflow

  secretObjects:
    - secretName: myapp-k8s-secret
      type: Opaque
      data:
        - objectName: myusername
          key: k8s-myusername
        - objectName: mypassword
          key: k8s-mypassword
        - objectName: myairflow
          key: k8s-myairflow